version: '3'
services: 
    n1:
        image: cassandra-with-cqlshrc
        networks: 
            - cluster
        environment: 
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=DC1
            - CASSANDRA_RACK=RAC1
    n2:
        image: cassandra-with-cqlshrc
        networks: 
            - cluster
        environment: 
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=DC1
            - CASSANDRA_RACK=RAC2
        depends_on: 
            - n1
    n3:
        image: cassandra-with-cqlshrc
        networks: 
            - cluster
        environment: 
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=DC1
            - CASSANDRA_RACK=RAC3
        depends_on: 
            - n1                       
networks: 
    cluster:
            